version: '3.17'

networks:
  python-network:
    driver: bridge

services:
  fastapi-app:
    container_name: FastAPI-app
    image: py-container
    ports:
      - '80:80'
#      - '443:443'
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - python-network
#    volumes:
#      - .:/usr/src/app


#services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#
#    env_file:
#      - .env
#    ports:
#      - "8000:8000"
#    depends_on:
#      db:
#        condition: service_started
