version: '3.17'

networks:
  e_learning_network:  # change container network
    driver: bridge

services:
  e-learning-app:  # change app name
    container_name: e-learning-app  # change container name
    image: e-learning # change image name
    ports:
      - '80:80'
#      - '443:443'
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - e_learning_network # change name
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:15.3
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - e_learning_network  # change name

volumes:
    db_data:
